minimumReleaseAge: 20160
minimumReleaseAgeExclude:
  - '@wentthefox-org/discord-bot-framework'

allowBuilds:
  '@prisma/engines': true
  bufferutil: true
  esbuild: true
  prisma: true
  unrs-resolver: true
  utf-8-validate: true
