name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DISCORD_BOT_TOKEN: MOCK_DISCORD_BOT_TOKEN
  DISCORD_CLIENT_ID: MOCK_DISCORD_CLIENT_ID
  TELEGRAM_BOT_TOKEN: MOCK_TELEGRAM_BOT_TOKEN

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: 'Building, Linting and Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set up Node.js v24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Prepare .env
        run: |
          cp .env.example .env

      - name: Generate Prisma client
        run: pnpm exec prisma generate

      - name: Run lint
        run: pnpm run lint

      - name: Build project
        run: pnpm run build

      - name: Start built-in PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo systemctl status postgresql.service
          sudo -u postgres psql -c "CREATE DATABASE fantastick;"
          sudo -u postgres psql -c "CREATE DATABASE fantastick_shadow;"
          sudo -u postgres psql -c "CREATE USER username PASSWORD 'password' SUPERUSER;"

      - name: Run Prisma migrations
        run: pnpm exec prisma migrate deploy

      - name: Run tests
        run: pnpm run test
